global:
  resolve_timeout: 5m
  #smtp_smarthost: '<SMTP_HOST>'
  #smtp_from: '<SMTP_FROM>'
  #smtp_auth_username: '<SMTP_AUTH_USERNAME>'
  #smtp_auth_password: '<SMTP_AUTH_PASSWORD>'



# The root route on which each incoming alert enters.
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 10s
  repeat_interval: 30m
  # Default receiver
  receiver: 'devopsteam'

  #Child routes
  routes:
  - match:
      severity: 'warning'
    group_by: ['alertname','instance']
    receiver: 'devopsteam'
    repeat_interval: 30m
    continue: true

  # subroute
  # If it's critical, repeat every 10 minutes
    routes:
    - match:
        severity: 'critical'
      repeat_interval: 10m
      continue: true



# Inhibit rules
inhibit_rules:
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'critical'
    # Apply inhibition if the alertname is the same.
    equal: ['instance']


# Receivers (email and slack)
receivers:
- name: 'devopsteam'

  # email_configs:
  # - to: '<EMAIL_TO>'
  #   send_resolved: true

  # slack_configs:
  # - channel: "alerts-channel"
  #   api_url: <SLACK_HOOK_ENDPOINT>
  #   send_resolved: true
  #   color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
  #   icon_url: https://avatars3.githubusercontent.com/u/3380462
  #   title: |-
  #    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
  #    {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
  #      {{" "}}(
  #      {{- with .CommonLabels.Remove .GroupLabels.Names }}
  #        {{- range $index, $label := .SortedPairs -}}
  #          {{ if $index }}, {{ end }}
  #          {{- $label.Name }}="{{ $label.Value -}}"
  #        {{- end }}
  #      {{- end -}}
  #      )
  #    {{- end }}
  #   text: |-
  #     {{ range .Alerts }}
  #       *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
  #       *Description:* {{ .Annotations.description }}
  #       *Details:*
  #       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
  #       {{ end }}
  #     {{ end }}
