groups:
  - name: SERVICES Rules
    rules:

      - alert: Docker_Service_Down
        expr: node_systemd_unit_state{name="docker.service",state="failed"} == 1
        for: 5m
        labels:
          severity: critical
          team: devops
        annotations:
          summary: "Docker service is down on {{ $labels.instance }}"
