apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  org_id: 1
  url: http://prometheus:9090
  jsonData:
     tlsSkipVerify: true
  is_default: true
  version: 1
  editable: true
